# Set cattpuccin-mocha as default color scheme
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

# Window settings
[window]
  # Make it borderless and without a title bar.
	decorations = "None"
  # Set the window position
	padding = {x=0, y=0}
  # Set the window opacity to be a little transparent
  # TODO: find a way to config this with a keybinding, so that it can be toggled
	opacity = 1

[font]
	normal = {family = "Hack Nerd Font Mono"}

[env]
  # Pretend to be xterm for color schemes.
  TERM = "xterm-256color"
