#!/bin/sh
#
# Automatically adds branch name and to every commit message.
#

NAME=$(git branch | grep '*' | sed 's/* //')
TEXT=$(<$1)

if [ -n "$TEXT" ]
then
    echo $NAME > $1
    echo "$TEXT" >> $1
else
    echo "Aborting commit due to empty commit message."
    exit 1
fi
