" be IMproved, required
set nocompatible
filetype off			" required
syntax on
set backspace=2   " Backspace deletes like most programs in insert mode
set nobackup
set nowritebackup
set ruler         " show the cursor position all the time
set showcmd       " display incomplete commands
set incsearch     " do incremental searching
set laststatus=2  " Always display the status line
set autowrite     " Automatically :write before running commands


" Relative Numbering
set relativenumber
set number

" Softtabs, 2 spaces
set tabstop=2
set shiftwidth=2
set shiftround
set expandtab

" Set clipboard compatibility
set clipboard=unnamed

" Make it obvious where 80 characters is
set textwidth=80
set colorcolumn=+2

" Vundle plugins
source ~/.dotfiles/vim/vimrc.vundle

" Put your non-Plugin stuff after this line

"if filereadable(expand("~/.vimrc_background"))
  let base16colorspace=256
  source ~/.vimrc_background
"endif
