set nocompatible  " be IMproved, required
filetype off			" required
syntax on
set backspace=2   " Backspace deletes like most programs in insert mode
set nobackup
set nowritebackup
set ruler         " show the cursor position all the time
set showcmd       " display incomplete commands
set incsearch     " do incremental searching
set laststatus=2  " Always display the status line
set autowrite     " Automatically :write before running commands
set mouse=a       " Enable mouse to move windows

" Set timeout to keys
set timeoutlen=1000 ttimeoutlen=0

" Relative Numbering
set relativenumber
set number

" Softtabs, 2 spaces
set tabstop=2
set shiftwidth=2
set shiftround
set expandtab

" Set clipboard compatibility
set clipboard=unnamed

" Make it obvious where 80 characters is
set textwidth=80
set wrapmargin=0
set colorcolumn=+2

" Smart case search, lowercase is insensitive and UPPERCASE is sensitive
" Overridewith \c (insensitive) or \C (sensitive)
set ignorecase
set smartcase

" Status Line configs
set laststatus=2

" Vundle plugins
source ~/.dotfiles/vim/vimrc.vundle

" runtime macros/matchit.vim

" Mappings
command Q q
command W w
" command WQ wq
" command Wq wq

nmap <leader>n :NERDTreeToggle<cr>
nnoremap <leader>. :CtrlPTag<cr>

