# Add dotfiles env and bin to path
export DOTFILES=$HOME/.dotfiles
export PATH=$DOTFILES/bin:$HOME/bin:/usr/local/bin:$PATH

# Source the configured path variables
test -e "${HOME}/.profile" && source "${HOME}/.profile"

# You may need to manually set your language environment
export LC_ALL="en_US.UTF-8"
export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
export EDITOR='nvim'

# You may need to manually set your language environment
export LC_ALL="en_US.UTF-8"
export LANG=en_US.UTF-8

TARGET_DIR=$DOTFILES/zsh/aliases
for file in "$TARGET_DIR"/*.zsh(N) ; do
    source "$file"
done

# Created by Zap installer
[ -f "${XDG_DATA_HOME:-$HOME/.local/share}/zap/zap.zsh" ] && source "${XDG_DATA_HOME:-$HOME/.local/share}/zap/zap.zsh"
plug "zsh-users/zsh-autosuggestions"
plug "zap-zsh/supercharge"
plug "zsh-users/zsh-syntax-highlighting"
plug "zsh-users/zsh-history-substring-search"

plug "zap-zsh/completions"
plug "chivalryq/git-alias"
plug "atoftegaard-git/zsh-omz-autocomplete"
plug "zap-zsh/fzf"
plug "wintermi/zsh-brew"
plug "MenkeTechnologies/zsh-expand"
# plug "sdiebolt/zsh-ssh-agent"

plug "MichaelAquilina/zsh-you-should-use"


eval "$(zoxide init zsh)"

# search history settings
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
export HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_FOUND=

export STARSHIP_CONFIG=$DOTFILES/starship/config.toml
eval "$(starship init zsh)"
