export DOTFILES=$HOME/.dotfiles
export XDG_CONFIG_HOME=$DOTFILES

export PATH=$DOTFILES/bin:$HOME/bin:$PATH

# Source the configured path variables
test -e "${HOME}/.profile" && source "${HOME}/.profile"

if type brew &>/dev/null; then
  eval "$(brew shellenv)"
  brew_prefix=$(brew --prefix)
  source $brew_prefix/opt/zinit/zinit.zsh
fi

export LC_ALL="en_US.UTF-8"
export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
export EDITOR='nvim'

# Aliases
TARGET_DIR=$DOTFILES/zsh/aliases
for file in "$TARGET_DIR"/*.zsh(N) ; do
    source "$file"
done

# Work environment
TARGET_DIR=$DOTFILES/zsh/work
for file in "$TARGET_DIR"/*.zsh(N) ; do
    source "$file"
done

setopt AUTO_CD
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_SAVE_NO_DUPS
setopt SHARE_HISTORY

# Key bindings
# bindkey -v  # vi mode
# bindkey '^x^e'  # edit line in editor
# bindkey '^r'  # backward search

if type zinit &>/dev/null; then
  zinit light zsh-users/zsh-syntax-highlighting
  zinit light zsh-users/zsh-completions
  zinit light zsh-users/zsh-autosuggestions

  zinit snippet OMZP::branch
  zinit snippet OMZP::brew
  zinit snippet OMZP::colored-man-pages
  zinit snippet OMZP::colorize
  zinit snippet OMZP::docker-compose
  zinit snippet OMZP::git
  zinit snippet OMZP::kubectl
  zinit snippet OMZP::python
  zinit snippet OMZP::ssh-agent
  zinit snippet OMZP::starship
  zinit snippet OMZP::zoxide
fi

# Disabled plugins
# zinit snippet OMZP::docker
# zinit snippet OMZP::gh
# zinit snippet OMZP::tmux

# ssh
zstyle :omz:plugins:ssh-agent identities github-Pedrobc89 github-shippo

autoload -Uz compinit
compinit
